### ISSUE TITLE
Build broken on Mac OS X

### ISSUE THREAD

**Issue by genehack** [sass/perl-libsass#26]
Currently getting a build error on MacOS X:

```
% make                                                                                                              21:05:25
"/opt/plenv/versions/5.24.0/bin/perl5.24.0" -MExtUtils::Command::MM -e 'cp_nonempty' -- Sass.bs blib/arch/auto/CSS/Sass/Sass.bs 644
rm -f blib/arch/auto/CSS/Sass/Sass.bundle
cc  -mmacosx-version-min=10.11 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong -o blib/arch/auto/CSS/Sass/Sass.bundle -Wl,--no-as-needed  -lstdc++   -Wl,--as-needed libsass/src/ast.o libsass/src/base64vlq.o libsass/src/bind.o libsass/src/cencode.o libsass/src/check_nesting.o libsass/src/color_maps.o libsass/src/constants.o libsass/src/context.o libsass/src/cssize.o libsass/src/emitter.o libsass/src/environment.o libsass/src/error_handling.o libsass/src/eval.o libsass/src/expand.o libsass/src/extend.o libsass/src/file.o libsass/src/functions.o libsass/src/inspect.o libsass/src/json.o libsass/src/lexer.o libsass/src/listize.o libsass/src/memory_manager.o libsass/src/node.o libsass/src/output.o libsass/src/parser.o libsass/src/plugins.o libsass/src/position.o libsass/src/prelexer.o libsass/src/remove_placeholders.o libsass/src/sass.o libsass/src/sass2scss.o libsass/src/sass_context.o libsass/src/sass_functions.o libsass/src/sass_util.o libsass/src/sass_values.o libsass/src/source_map.o libsass/src/to_c.o libsass/src/to_value.o libsass/src/units.o libsass/src/utf8_string.o libsass/src/util.o libsass/src/values.o Sass.o  \
              \

ld: unknown option: --no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [blib/arch/auto/CSS/Sass/Sass.bundle] Error 1
```

Looks like it may be related to the change in #25 ?

**Comment by genehack** [comment]
This is with CSS::Sass 3.3.6, EUMM 7.18, and perl 5.24.0.

I got the build to complete by removing both the `--no-as-needed` and `--as-needed` bits from the generated `Makefile`, so it seems like the logic around line 308 in `Makefile.PL` needs to be amended _somehow_. I don't really understand what's going on there, so I'm unable to offer a lot of concrete suggestions other than adding a `unless ($^O eq 'darwin')` guard clause around the whole thing...

**Comment by joshdekock** [comment]
It looks like clang is being recognised as gcc by `ExtUtils::CppGuess`, so maybe it's more of a downstream issue? (although not one that couldn't be fixed here)

**Comment by mgreter** [comment]
Pretty sure that's the case, I'm sorry but I haven't had the time to look into it. Mostly also because I don't have a mac at hand, but I expect it should be the same if you use clang on linux. Maybe somebody could figure out how to detect clang reliably, so I could add another condition for it.

**Comment by joshdekock** [comment]
@mgreter you could check for the `__clang__` define in the output of `echo | $(CC) -dM -E -`

**Comment by mgreter** [comment]
I'm a bit worried about how to reliably run such a command across various different platforms though ...

**Comment by mgreter** [comment]
I've added another fix and also an upper bound when the previous fix is applied. The easiest way then to fix this issue is to update ExtUtils-MakeMaker to version 7.20+. In case we detect a buggy EUMM version and `ld` does not support `--no-as-needed` we print a message to tell users to update their EUMM and exit. Maybe somebody could test current [develop branch] [1] on OS x with various versions of EUMM?

[1]: https://github.com/sass/perl-libsass/tree/develop

You can install different versions of EUMM via:
`cpan BINGOS/ExtUtils-MakeMaker-7.8.tar.gz` // last working version
`cpan BINGOS/ExtUtils-MakeMaker-7.10.tar.gz` // first buggy version
`cpan BINGOS/ExtUtils-MakeMaker-7.18.tar.gz` // last buggy version
`cpan BINGOS/ExtUtils-MakeMaker-7.20.tar.gz` // first fixed version

Thanks!

**Comment by jberger** [comment]
The `develop` branch does indeed get me past the `--no-as-needed` build error. I do then get a new failure:

```
t/00_sanity.t ........... 1/3 
#   Failed test 'Have compatible version'
#   at t/00_sanity.t line 21.
#          got: '3.3.'
#     expected: '3.4.'
# Looks like you failed 1 test of 3.
t/00_sanity.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

**Comment by mgreter** [comment]
Yep, have this on the radar. Its because libsass tagged a new "major" version (libsass doesn't strictly adhere to semver yet). But no real changes needed for perl-libsass, but wanted to wait until release notes are properly done. Anyway, thanks for the heads up. Nice to know people are actually using it!
