### ISSUE TITLE
UTF-8 in input causes warning and smash to Latin-1 on output

### ISSUE THREAD

**Issue by tangentsoft** [sass/perl-libsass#37]
My `.scss` files use some UTF-8 characters beyond Latin-1 and ASCII in their comments.  This causes warnings like this:

     "\x{00a9}" does not map to ascii at /usr/local/bin/psass line 275.

It also causes the hex escape sequence to be put into the output file at the corresponding location, not the UTF-8 value from the input file.

SInce this is in comments so far, it's mostly harmless, but it would be nice if I could tell `psass` what encoding to use when opening my input files so this wouldn't happen.

**Comment by mgreter** [comment]
This issue might be a bit more complex than at a first look. First libsass and perl-libsass both are fully utf8 aware (beside that no other encoding is currently supported due to the lack of translation tables between them in libsass). On the other hand, `psass` tries to be smart when printing stuff to your console. In order to do that it [tries to determine what encoding your console is set to](https://www.perl.com/pub/2012/04/perlunicook-decode-standard-filehandles-as-locale-encoding.html/). In your case it seems to be set to `ascii`.

I guess you redirect the output to a file via `>`? I don't really know how the console encoding influences stream redirects, but I would suggest to just pass the output filename as a second option to `psass`.
If I'm not wrong this should fix your issue.

Thanks and have a nice day!

**Comment by mgreter** [comment]
Just checked locally how the file redirect influences this. The output by `psass` will be in the encoding of your terminal. In my case (on windows) it is `cp850` and it was able to convert latin1 characters, but gave the same warning for chinese characters. The resulting file is then also encoded as `cp850`.

Therefore I recommend to either let psass write the file or change your terminal to utf8.

We could default stdin/stdout/stderr to utf8, which would probably solve your issue, but would also introduce quite a few other issues, beside being technically incorrect. We also can't know if the output will be redirected to a file or not. Therefore there is not much to do here anymore.
