### ISSUE TITLE
Deprecation plans

### ISSUE THREAD

**Issue by stof** [sass/perl-libsass#52]
Now that [libsass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated), what are the plans for this project ? Should it be marked as deprecated as well ?

**Comment by mgreter** [comment]
I'm reluctant to call it dead, since as the (as it seems) only remaining developer of LibSass I'm currently in the process of getting the next big LibSass release ready. Albeit very slowly.  I'll leave this issue report open so people know that the state of LibSass is currently not very optimal. But the next big Release is on the brink, although it does seem like some famous last words. So let me come back to this in a few months :)

**Comment by ulgens** [comment]
Can we please revisit this? The latest commit and release was 2 years ago and at this point libsass is clearly deprecated. A deprecation warning in the readme and archival of this repostory would be really nice.
